export const getLuminaTheme = (isDark) => {
    const c = isDark
      ? {
          base: "#9be963",
          tag: "#ec7882",
          string: "#9be963",
          keyword: "#cc7bf4",
          number: "#5de7e7",
          comment: "#6e6e68",
          function: "#7ec8e3",
          operator: "#e6e4df",
          punctuation: "#d3d7de",
          property: "#f47b85",
          constant: "#5de7e7",
          builtin: "#cc7bf4",
          attr: "#ec7882", 
        }
      : {
          base: "#2d2b29",
          tag: "#c0404a",
          string: "#5a8a2e",
          keyword: "#8b4dbf",
          number: "#2a9d9d",
          comment: "#888880",
          function: "#2a7a9d",
          operator: "#2d2b29",
          punctuation: "#666660",
          property: "#bb1421",
          constant: "#2a9d9d",
          builtin: "#8b4dbf",
          attr: "#c0404a",
        };
  
    return {
      'code[class*="language-"]': { color: c.base, background: "transparent" },
      'pre[class*="language-"]': { color: c.base, background: "transparent" },
      comment: { color: c.comment, fontStyle: "italic" },
      prolog: { color: c.comment },
      doctype: { color: c.comment },
      cdata: { color: c.comment },
      punctuation: { color: c.punctuation },
      property: { color: c.property },
      tag: { color: c.tag },
      boolean: { color: c.number },
      number: { color: c.number },
      constant: { color: c.constant },
      symbol: { color: c.number },
      selector: { color: c.keyword },
      "attr-name": { color: c.attr },
      string: { color: c.string },
      char: { color: c.string },
      builtin: { color: c.builtin },
      operator: { color: c.operator },
      entity: { color: c.property },
      url: { color: c.string },
      keyword: { color: c.keyword },
      regex: { color: c.string },
      important: { color: c.keyword, fontWeight: "bold" },
      variable: { color: c.base },
      function: { color: c.function },
      "class-name": { color: c.function },
      "attr-value": { color: c.string },
      atrule: { color: c.keyword },
      inserted: { color: c.string },
      deleted: { color: c.tag },
    };
  };